apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: sammika/web:7.0
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: web-configmap
                  key: backend_url
            # - name: REACT_APP_BACKEND_PORT
            #   valueFrom:
            #     configMapKeyRef:
            #       name: web-configmap
            #       key: backend_port
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web

  type: NodePort

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30006
